# Generated by Django 6.1 on 2026-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("primary_color", models.CharField(default="#1F1D1B", max_length=20)),
                ("accent_color", models.CharField(default="#B08D3E", max_length=20)),
                (
                    "background_color",
                    models.CharField(default="#FDFBF7", max_length=20),
                ),
                (
                    "font_pair",
                    models.CharField(default="Playfair Display, Inter", max_length=100),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
