# Generated by Django 6.1 on 2026-09-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_bestseller",
            field=models.BooleanField(default=False),
        ),
    ]
