# Generated by Django 6.1 on 2026-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_is_bestseller"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="category",
            name="show_on_homepage",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Lower number shows first"
            ),
        ),
    ]
