# Generated by Django 6.1 on 2026-09-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_image_category_show_on_homepage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="products/videos/")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
    ]
