# Generated by Django 6.1 on 2026-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="line1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="line2",
        ),
        migrations.AddField(
            model_name="address",
            name="area",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="address",
            name="flat",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="address",
            name="full_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="address",
            name="landmark",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="address",
            name="mobile_number",
            field=models.CharField(default="", max_length=15),
        ),
    ]
