# Generated by Django 6.1 on 2026-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_address_line1_remove_address_line2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="address",
            name="landmark",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="address",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
